name: "Insites SDK"
on:
  release:
    types:
      - created
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-v1-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-v1-

      - name: Install dependencies
        run: COMPOSER_DISCARD_CHANGES=true composer install --prefer-dist --no-progress

      - name: PHPStan
        run: if [ -f vendor/bin/phpstan ]; then php -d memory_limit=4G vendor/bin/phpstan analyse -l 5 src; fi

      - name: Run Unit tests
        run: if [ -f vendor/bin/phpunit ]; then vendor/bin/phpunit; fi